"""add target_comments

Revision ID: aa790763e496
Revises: d5479589ca7b
Create Date: 2026-06-23 19:14:45.431516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa790763e496'
down_revision: Union[str, Sequence[str], None] = 'd5479589ca7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_jobs', sa.Column('target_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_jobs', 'target_comments')
    # ### end Alembic commands ###
